const projectTypes = {
  development: [
    "Website",
    "E-Commerce",
    "Dashboard",
    "Landing Page",
    "Portfolio",
    "CRM System",
    "ERP System",
    "SaaS Platform",
    "Booking System",
    "Learning Platform",
    "API Development",
    "AI Integration",
  ],

  mobile: [
    "Android App",
    "iOS App",
    "Cross Platform App",
    "E-Commerce App",
    "Food Delivery",
    "Taxi App",
    "Chat App",
    "Healthcare App",
    "Fitness App",
    "FinTech App",
    "Social Media App",
    "Game",
  ],

  design: [
    "Website UI",
    "Mobile UI",
    "UX Research",
    "Logo Design",
    "Brand Identity",
    "Dashboard Design",
    "Presentation",
    "Social Media Design",
    "Packaging Design",
    "Illustrations",
  ],

  marketing: [
    "SEO",
    "Google Ads",
    "Facebook Ads",
    "Instagram Ads",
    "TikTok Ads",
    "Snapchat Ads",
    "Email Marketing",
    "Marketing Strategy",
    "Content Marketing",
    "Affiliate Marketing",
  ],

  media: [
    "Video Editing",
    "Motion Graphics",
    "Commercial Video",
    "Photography",
    "Videography",
    "YouTube Editing",
    "Reels",
    "Podcast",
    "Animation",
    "Voice Over",
  ],

  content: [
    "Copywriting",
    "Blog Writing",
    "Technical Writing",
    "Product Description",
    "Script Writing",
    "Translation",
    "Social Media Content",
    "Email Content",
  ],

  ai: [
    "AI Chatbot",
    "Machine Learning",
    "Deep Learning",
    "Computer Vision",
    "NLP",
    "Recommendation System",
    "Data Analysis",
    "AI Automation",
  ],

  security: [
    "Penetration Testing",
    "Security Audit",
    "Network Security",
    "Cloud Security",
    "Ethical Hacking",
    "SOC",
    "Compliance",
  ],

  business: [
    "Business Analysis",
    "HR",
    "Accounting",
    "Sales",
    "Legal",
    "Project Management",
    "Startup Consulting",
  ],
};

export default projectTypes;